name: clang-format Linter
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './Rectangless'
        exclude: './lib'
        extensions: 'h,cpp,c'
        clangFormatVersion: 11
        inplace: True
    
    - uses: EndBug/add-and-commit@v4
